function chords_with_bass = get_chords_bass(chords_number, bass_time)

     dictionary_chords = { 'C', 'C/C#','C/D','C/Eb','C/E','C/F','C/F#','C/G','C/G#','C/A','C/Bb','C/B', ...
 'Cm','Cm/C#','Cm/D','Cm/Eb','Cm/E','Cm/F','Cm/F#','Cm/G','Cm/G#','Cm/A','Cm/Bb','Cm/B', ...
 'Caum','Caum/C#','Caum/D','Caum/Eb','Eaum','Caum/F','Caum/F#','Caum/G','G#aum','Caum/A','Caum/Bb','Caum/B', ...
 'Cdim','Cdim/C#','Cdim/D','Cdim/Eb','Cdim/E','Cdim/F','Cdim/F#','Cdim/G','Cdim/G#','Cdim/A','Cdim/Bb','Cdim/B', ...
 'C#/C', 'C#','C#/D','C#/Eb','C#/E','C#/F','C#/F#','C#/G','C#/G#','C#/A','C#/Bb','C#/B', ...
 'C#m/C','C#m','C#m/D','C#m/Eb','C#m/E','C#m/F','C#m/F#','C#m/G','C#m/G#','C#m/A','C#m/Bb','C#m/B', ...
 'C#aum/C','C#aum','C#aum/D','C#aum/Eb','C#aum/E','Faum','C#aum/F#','C#aum/G','C#aum/G#','Aaum','C#aum/Bb','C#aum/B', ...
 'C#dim/C','C#dim','C#dim/D','C#dim/Eb','C#dim/E','C#dim/F','C#dim/F#','C#dim/G','C#dim/G#','C#dim/A','C#dim/Bb','C#dim/B', ...
 'D/C', 'D/C#','D','D/Eb','D/E','D/F','D/F#','D/G','D/G#','D/A','D/Bb','D/B', ...
 'Dm/C','Dm/C#','Dm','Dm/Eb','Dm/E','Dm/F','Dm/F#','Dm/G','Dm/G#','Dm/A','Dm/Bb','Dm/B', ...
 'Daum/C','Daum/C#','Daum','Daum/Eb','Daum/E','Daum/F','F#aum','Daum/G','Daum/G#','Daum/A','Bbaum','Daum/B', ...
 'Ddim/C','Ddim/C#','Ddim','Ddim/Eb','Ddim/E','Ddim/F','Ddim/F#','Ddim/G','Ddim/G#','Ddim/A','Ddim/Bb','Ddim/B', ...
 'Eb/C', 'Eb/C#','Eb/D','Eb','Eb/E','Eb/F','Eb/F#','Eb/G','Eb/G#','Eb/A','Eb/Bb','Eb/B', ...
 'Ebm/C','Ebm/C#','Ebm/D','Ebm','Ebm/E','Ebm/F','Ebm/F#','Ebm/G','Ebm/G#','Ebm/A','Ebm/Bb','Ebm/B', ...
 'Ebaum/C','Ebaum/C#','Ebaum/D','Ebaum','Ebaum/E','Ebaum/F','Ebaum/F#','Gaum','Ebaum/G#','Ebaum/A','Ebaum/Bb','Baum', ...
 'Ebdim/C','Ebdim/C#','Ebdim/D','Ebdim','Ebdim/E','Ebdim/F','Ebdim/F#','Ebdim/G','Ebdim/G#','Ebdim/A','Ebdim/Bb','Ebdim/B', ...
 'E/C', 'E/C#','E/D','E/Eb','E','E/F','E/F#','E/G','E/G#','E/A','E/Bb','E/B', ...
 'Em/C','Em/C#','Em/D','Em/Eb','Em','Em/F','Em/F#','Em/G','Em/G#','Em/A','Em/Bb','Em/B', ...
 'Caum','Eaum/C#','Eaum/D','Eaum/Eb','Eaum','Eaum/F','Eaum/F#','Eaum/G','G#aum','Eaum/A','Eaum/Bb','Eaum/B', ...
 'Edim/C','Edim/C#','Edim/D','Edim/Eb','Edim','Edim/F','Edim/F#','Edim/G','Edim/G#','Edim/A','Edim/Bb','Edim/B', ...
 'F/C', 'F/C#','F/D','F/Eb','F/E','F','F/F#','F/G','F/G#','F/A','F/Bb','F/B', ...
 'Fm/C','Fm/C#','Fm/D','Fm/Eb','Fm/E','Fm','Fm/F#','Fm/G','Fm/G#','Fm/A','Fm/Bb','Fm/B', ...
 'Faum/C','C#aum','Faum/D','Faum/Eb','Faum/E','Faum','Faum/F#','Faum/G','Faum/G#','Aaum','Faum/Bb','Faum/B', ...
 'Fdim/C','Fdim/C#','Fdim/D','Fdim/Eb','Fdim/E','Fdim','Fdim/F#','Fdim/G','Fdim/G#','Fdim/A','Fdim/Bb','Fdim/B', ...
 'F#/C', 'F#/C#','F#/D','F#/Eb','F#/E','F#/F','F#','F#/G','F#/G#','F#/A','F#/Bb','F#/B', ...
 'F#m/C','F#m/C#','F#m/D','F#m/Eb','F#m/E','F#m/F','F#m','F#m/G','F#m/G#','F#m/A','F#m/Bb','F#m/B', ...
 'F#aum/C','F#aum/C#','Daum','F#aum/Eb','F#aum/E','F#aum/F','F#aum','F#aum/G','F#aum/G#','F#aum/A','Bbaum','F#aum/B', ...
 'F#dim/C','F#dim/C#','F#dim/D','F#dim/Eb','F#dim/E','F#dim/F','F#dim','F#dim/G','F#dim/G#','F#dim/A','F#dim/Bb','F#dim/B', ...
 'G/C', 'G/C#','G/D','G/Eb','G/E','G/F','G/F#','G','G/G#','G/A','G/Bb','G/B', ...
 'Gm/C','Gm/C#','Gm/D','Gm/Eb','Gm/E','Gm/F','Gm/F#','Gm','Gm/G#','Gm/A','Gm/Bb','Gm/B', ...
 'Gaum/C','Gaum/C#','Gaum/D','Ebaum','Gaum/E','Gaum/F','Gaum/F#','Gaum','Gaum/G#','Gaum/A','Gaum/Bb','Baum', ...
 'Gdim/C','Gdim/C#','Gdim/D','Gdim/Eb','Gdim/E','Gdim/F','Gdim/F#','Gdim','Gdim/G#','Gdim/A','Gdim/Bb','Gdim/B', ...
 'G#/C', 'G#/C#','G#/D','G#/Eb','G#/E','G#/F','G#/F#','G#/G','G#','G#/A','G#/Bb','G#/B', ...
 'G#m/C','G#m/C#','G#m/D','G#m/Eb','G#m/E','G#m/F','G#m/F#','G#m/G','G#m','G#m/A','G#m/Bb','G#m/B', ...
 'Caum','G#aum/C#','G#aum/D','G#aum/Ebaum','Eaum','G#aum/F','G#aum/F#','G#aum/G','G#aum','G#aum/A','G#aum/Bb','G#aum/B', ...
 'G#dim/C','G#dim/C#','G#dim/D','G#dim/Eb','G#dim/E','G#dim/F','G#dim/F#','G#dim/G','G#dim','G#dim/A','G#dim/Bb','G#dim/B', ...
 'A/C', 'A/C#','A/D','A/Eb','A/E','A/F','A/F#','A/G','A/G#','A','A/Bb','A/B', ...
 'Am/C','Am/C#','Am/D','Am/Eb','Am/E','Am/F','Am/F#','Am/G','Am/G#','Am','Am/Bb','Am/B', ...
 'Aaum/C','C#aum','Aaum/D','Aaum/Ebaum','Aaum/Eaum','Faum','Aaum/F#','Aaum/G','Aaum/G#','Aaum','Aaum/Bb','Aaum/B', ...
 'Adim/C','Adim/C#','Adim/D','Adim/Eb','Adim/E','Adim/F','Adim/F#','Adim/G','Adim/G#','Adim','Adim/Bb','Adim/B', ...
 'Bb/C', 'Bb/C#','Bb/D','Bb/Eb','Bb/E','Bb/F','Bb/F#','Bb/G','Bb/G#','Bb/A','Bb','Bb/B', ...
 'Bbm/C','Bbm/C#','Bbm/D','Bbm/Eb','Bbm/E','Bbm/F','Bbm/F#','Bbm/G','Bbm/G#','Bbm/A','Bbm','Bbm/B', ...
 'Bbaum/C','Bbaum/C#','Daum','Bbaum/Ebaum','Bbaum/Eaum','Bbaum/F','F#aum','Bbaum/G','Bbaum/G#','Bbaum/A','Bbaum','Bbaum/B', ...
 'Bbdim/C','Bbdim/C#','Bbdim/D','Bbdim/Eb','Bbdim/E','Bbdim/F','Bbdim/F#','Bbdim/G','Bbdim/G#','Bbdim/A','Bbdim','Bbdim/B', ...
 'B/C', 'B/C#','B/D','B/Eb','B/E','B/F','B/F#','B/G','B/G#','B/A','B/Bb','B', ...
 'Bm/C','Bm/C#','Bm/D','Bm/Eb','Bm/E','Bm/F','Bm/F#','Bm/G','Bm/G#','Bm/A','Bm/Bb','Bm', ...
 'Baum/C','Baum/C#','Baum/D','Ebaum','Baum/Eaum','Baum/F','Baum/F#','Gaum','Baum/G#','Baum/A','Baum/Bb','Baum', ...
 'Bdim/C','Bdim/C#','Bdim/D','Bdim/Eb','Bdim/E','Bdim/F','Bdim/F#','Bdim/G','Bdim/G#','Bdim/A','Bdim/Bb','Bdim'};


 % build chords with bass to translate to dictionary
 chords_with_bass_number = {};
 chord_iterator = 1;
 for chord = 1:48
 	for bass = 1:12
 		chords_with_bass_number{chord_iterator} = [chord, bass];
 		chord_iterator = chord_iterator + 1;
 	end
 end

 chords_with_bass = {};
 for time = 1:length(chords_number)
 	 for chord = 1:length(chords_with_bass_number)
 	 	peer_chord = chords_with_bass_number{chord};
 	 	if peer_chord(1) == chords_number(time) && peer_chord(2) == bass_time(time)
 	 		chords_with_bass{time} = dictionary_chords{chord};
 	 	end
 	 end
 end

end